%%%%% Band Pass Filter to extract the alpha band from the signal x %%%%%

function y = BPF_alpha(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Mar-2023 03:22:08

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 8;    % Order
    % Fpass1 = 8;    % First Passband Frequency
    % Fpass2 = 13;   % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 200;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.81246782855441 0.973578547943531; 1 0 -1 1 ...
        -1.92046497535774 0.983251570062645; 1 0 -1 1 -1.82276547949412 ...
        0.943565664041202; 1 0 -1 1 -1.87163258713811 0.953252563399159], ...
        'ScaleValues', [0.0770941848251174; 0.0770941848251174; ...
        0.0405060663966982; 0.0405060663966982; 0.891250938133746]);
end

s = double(x);
y = step(Hd,s);

