%%%%% Band Pass Filter to extract the gamma band from the signal x %%%%%

function y = BPF_gamma(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Mar-2023 03:26:19

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 8;    % Order
    % Fpass = 30;   % Passband Frequency
    % Apass = 1;    % Passband Ripple (dB)
    % Fs    = 200;  % Sampling Frequency
    %
    % h = fdesign.highpass('n,fp,ap', N, Fpass, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -2 1 1 -1.13929931923066 0.944665295852922; 1 -2 1 1 ...
        -0.855358652142811 0.812686799302792; 1 -2 1 1 -0.215922097895293 ...
        0.595901258460824; 1 -2 1 1 0.743693447632869 0.295596499040334], ...
        'ScaleValues', [0.770991153770896; 0.667011362861401; ...
        0.452955839089029; 0.137975762851866; 0.891250938133746]);
end

s = double(x);
y = step(Hd,s);

