%%%%% Band Pass Filter to extract the theta band from the signal x %%%%%

function y = BPF_theta(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Mar-2023 03:18:23

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 8;    % Order
    % Fpass1 = 4;    % First Passband Frequency
    % Fpass2 = 8;    % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 200;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.91560644338669 0.977086141355179; 1 0 -1 1 ...
        -1.97242569666228 0.988267408225057; 1 0 -1 1 -1.91168427994803 ...
        0.952763694829395; 1 0 -1 1 -1.94109949022116 0.964307722730117], ...
        'ScaleValues', [0.0618287256793793; 0.0618287256793793; ...
        0.0325550706167754; 0.0325550706167754; 0.891250938133746]);
end

s = double(x);
y = step(Hd,s);

