%%%%% Band Pass Filter to extract the beta band from the signal x %%%%%

function y = BPF_beta(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Mar-2023 03:22:53

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 8;    % Order
    % Fpass1 = 13;   % First Passband Frequency
    % Fpass2 = 30;   % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 200;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.13000555394624 0.909142128954424; 1 0 -1 1 ...
        -1.79126371867498 0.953916360439713; 1 0 -1 1 -1.32559315150388 ...
        0.810157002289038; 1 0 -1 1 -1.60721256511839 0.856798380761394], ...
        'ScaleValues', [0.253357935993871; 0.253357935993871; ...
        0.131717874334378; 0.131717874334378; 0.891250938133746]);
end

s = double(x);
y = step(Hd,s);

