%%%%% Band Pass Filter to extract the delta band from the signal x %%%%%

function y = BPF_delta(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 27-Mar-2023 03:01:08

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N      = 8;    % Order
    % Fpass1 = 0.5;  % First Passband Frequency
    % Fpass2 = 4;    % Second Passband Frequency
    % Apass  = 1;    % Passband Ripple (dB)
    % Fs     = 200;  % Sampling Frequency
    %
    % h = fdesign.bandpass('n,fp1,fp2,ap', N, Fpass1, Fpass2, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.95789711639199 0.973199712687764; 1 0 -1 1 ...
        -1.99629407638508 0.99654453259674; 1 0 -1 1 -1.94133181696631 ...
        0.946753127599478; 1 0 -1 1 -1.98008298894115 0.980776610096598], ...
        'ScaleValues', [0.0541661186326607; 0.0541661186326607; ...
        0.0285531920133534; 0.0285531920133534; 0.891250938133746]);
end

s = double(x);
y = step(Hd,s);

